### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by Play2KillTV** [UnknowG/PlayerAnnouncements#2]
It does not work on me it says
[15:07:34] [Server thread/CRITICAL]: ErrorException: "Invalid argument supplied for foreach()" (EXCEPTION) in "plugins/PlayerAnnouncements.phar/src/UnknowG/PlayerAnnouncement/Commands/AnnouncementCommand" at line 34

And kicks me out of the server saying it is an internal error

**Comment by UnknowG** [comment]
Hello, Thank you for your report, I could have the command with the same text that you wanted to execute?

**Comment by Play2KillTV** [comment]
I tried doing /pa and the server said internal server error.

**Comment by UnknowG** [comment]
i can have screenshot in console ?

**Comment by Play2KillTV** [comment]
Strange it is working now I just cleared the console but no announcement is
showing. I did /pa and wrote a message. Is it supposed to not show?

**Comment by UnknowG** [comment]
show /pview (true or false)

**Comment by Play2KillTV** [comment]
I did pview to true. But the item I am holding is not showing up.

**Comment by UnknowG** [comment]
show your playersData.json

**Comment by Play2KillTV** [comment]
There is no .json format here sorry.

**Comment by UnknowG** [comment]
I see where I come from, create a playersData.yml file and restart your server

**Comment by Play2KillTV** [comment]
Heres the playerdata.yml

**Comment by UnknowG** [comment]
plugins_data/PlayersAnnouncelents

**Comment by UnknowG** [comment]
If your problem is solved close issue

**Comment by Play2KillTV** [comment]
Sorry things escalated quickly so I did not have time. Anyways thank you
for helping me out!

**Comment by UnknowG** [comment]
Is the problem solved?

**Comment by Play2KillTV** [comment]
No and I think it won't be resolved.

**Comment by UnknowG** [comment]
I'll install the plugin on my test server to see if I have the same error because I think it's weird I'll keep you informed

**Comment by Play2KillTV** [comment]
Ok thank you

**Comment by Play2KillTV** [comment]
Found player announcements clicked it and showed this.

**Comment by UnknowG** [comment]
I'm not very well understood.

**Comment by Play2KillTV** [comment]
Of what?

**Comment by UnknowG** [comment]
https://github.com/UnknowG/PlayerAnnouncements/issues/2#issuecomment-514618512
This.

**Comment by UnknowG** [comment]
I think I found it, I'm with a friend who knows a little better. We will have to wait for the next update on the plugins. Or upload it directly to GitHub so I close the issue 

Thank you for waiting, if any other problem opens a issue

**Comment by Play2KillTV** [comment]
Thanks
