### ISSUE TITLE
Like this?

### ISSUE THREAD

**Issue by Play2KillTV** [UnknowG/PlayerAnnouncements#3]
Is it supposed to look like this? I set pview to true.
![Screenshot_20190731-083225_Minecraft](https://user-images.githubusercontent.com/45384851/62174883-1a44c600-b36e-11e9-8dc7-5cf8a3ee14fa.jpg)

**Comment by UnknowG** [comment]
Hello. if it's true its mean you see, on the contrary if you put false you do not see

**Comment by UnknowG** [comment]
You downloaded which version? poggit or github?

**Comment by Play2KillTV** [comment]
Yeah I set it to true. So if someone does /pa (message). What am I going to
see on the chat if pview is true?

**Comment by Play2KillTV** [comment]
Github

**Comment by UnknowG** [comment]
pa view = true =  SHOW Ads
pa view = false = HIDE adw

**Comment by UnknowG** [comment]
![Screenshot_20190731-024333_Samsung Internet](https://user-images.githubusercontent.com/51505384/62175227-1ba9ca80-b33d-11e9-9728-6bae403d15c2.jpg)

2.0.2 is submit you just have to wait for the confirmation of the reviewers

**Comment by UnknowG** [comment]
Personally I'm going to sleep
Ask your questions I will answer you tomorrow morning. and please try to explain better because I do not understand what you mean.

**Comment by Play2KillTV** [comment]
Oh ok sorry im from asia its morning here

**Comment by UnknowG** [comment]
Oh ok you here is ?

**Comment by UnknowG** [comment]
Do you have any further questions or is the problem solved?

**Comment by Play2KillTV** [comment]
Can you show me what will really happen if you do /pa? I need to see if it
also does the same thing as mine.

**Comment by Play2KillTV** [comment]
I get it now. Because I thought that is you do /pa it will also broadcast
on what type of item you are holding. Sorry again.

**Comment by UnknowG** [comment]
I'm currently busy I'm coming back on your issue in 1-2day

**Comment by UnknowG** [comment]
This is /pa (message)


Good day.
