### ISSUE TITLE
Can't fix

### ISSUE THREAD

**Issue by Play2KillTV** [UnknowG/PlayerAnnouncements#4]
ErrorException: "Invalid argument for foreach ()" (EXCEPTION) in "plugins / PlayerAnnouncements_dev-61.phar / src / UnknowG / PlayerAnnouncement / Commands / AnnouncementCommand" at line 36

Was gonna fix but idk whats the problem

**Comment by UnknowG** [comment]
Hey, This version is still under development does not download it. waiting for it to be finalized, I have some problem in my life that prevents me from developing

**Comment by Play2KillTV** [comment]
Oh... Well, good luck on your problems. You can overcome it.

**Comment by UnknowG** [comment]
Do not worry, it's nothing serious. I will continue PA to week end. or tonight if I have the time.
